[project]
name = "secscripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dnspython>=2.7.0",
    "paramiko>=3.5.1",
    "requests>=2.32.3",
    "scapy>=2.6.1",
    "telnetlib3>=2.0.4",
]
